### ISSUE TITLE
Intro to CSS

### ISSUE THREAD

**Issue by jshawl** [ga-dc/pbj#108]
https://trello.com/c/9ic8Pk2Y/5-intro-to-css

**Comment by jshawl** [comment]
https://github.com/ga-dc/pbj/blob/aefa350859f2253ac954c0ac350f19063ee57c22/01-front-end-fundamentals/css/readme.md

**Comment by andrewsunglaekim** [comment]
delta - Faltered a bit on code along. Should make sure i'm not thrown off by the ordering of the styles that are coded

plus - whiteboarding CSS terms as they came up in the lesson, additionally reviewing each term with respect to learning objective
