### ISSUE TITLE
Edit to jQuery: Part I file 

### ISSUE THREAD

**Issue by leighvarley** [ga-dc/pbj#137]
Edit to jQuery: Part I file 

Under "What is jQuery?" heading text reads "The "Write More, Do Less" JS library" --
Should read "The write less, do more" library.

Also, the jQuery lesson is not included in the main WDI coursebook (http://ga-dc.github.io/pbj/02-intermediate-front-end/readme.html)

**Comment by jshawl** [comment]
Thanks leigh!!!
