### ISSUE TITLE
Git Life Lessons

### ISSUE THREAD

**Issue by karldonus** [ga-dc/pbj#138]
As a general newbie to not only Git, but the command line, I find some parallels.

I'm starting to appreciate the *asterisk*. It can make dealing with large quantities of files less of a hassle. For example, I'm a fan of "git add .", but I always check "git status" afterward to double check. But what if I modify, let's say an HTML file for shits and giggles...but it has no real bearing on my project? Wouldn't it be cool if there were a keyword that could exclude .html? Well, that's where the asterisk comes into play by helping select files that ought to be excluded in the commit. Neat.

Also, I thought we hadn't touched on how to pull up past edits...but we did! Little did I know, "git checkout <past commit>" is the command to jump into a time machine. I was worried about changing accidentally changing the "past", but rest assured, this view is relatively safe from being modified. HOWEVER, any changes made within the file won't be saved.

**Comment by jshawl** [comment]
:+1:
