### ISSUE TITLE
git vs subversion

### ISSUE THREAD

**Issue by arkinjb** [ga-dc/pbj#140]
The Atlassian Git tutorial made numerous references to SVN (Subversion) as another version control system. I had never heard of it so I looked it up. 
Most of what I found was comparisons between Subversion and Git. And while both have pros and cons, in most cases, it seems that Git came out ahead. 
The biggest difference is that Git is a distributed version control system while SVN is a centralized vcs. This means that Git uses local repositories as well as a central repository. This is useful for a few reasons:
1. independent workflow - developers can start with the same code (after fork/clone) but can each work on their own project independent of other changes
2. developers don't have to be connected to the central repo at all times - can save work locally
3. local repos work as a sort of backup system in the event that something happens to the central server.

One of the more in-depth reviews I found is located here: http://www.codeforest.net/git-vs-svn

**Comment by jshawl** [comment]
:+1:
