### ISSUE TITLE
Things I Learned - Alex Bannon

### ISSUE THREAD

**Issue by alexbannon** [ga-dc/pbj#141]
comfort: 5/5
completeness: 5/5

I learned about rebasing, the ability in git to make a branch part of the linear history of master. This is used instead of merge, which allows a branch to reform with the original master branch. Instead, it allows for a cleaner history, showing all the commits as part of a single branch.

It's useful when you're trying to collaborate on a project you don't really participate that much in. This way, you can create a branch, do your work, and then rebase, allowing the overseer of the branch to do what is essentially a fast-forward instead of a merge/fast forward.

**Comment by jshawl** [comment]
:+1:
