### ISSUE TITLE
Git HW branching and merging

### ISSUE THREAD

**Issue by pdavies88** [ga-dc/pbj#145]
Comfort_Level: 5
Completeness: 5
With merge strategies, many developers like to use fast-forward merges (facilitated through rebasing) for small features or bug fixes, while reserving 3-way merges for the integration of longer-running features. Fast-forward is a common workflow for short-lived topic branches that are used more as an isolated development than an organizational tool for longer-running features.

**Comment by jshawl** [comment]
:+1:
