### ISSUE TITLE
Learning Git

### ISSUE THREAD

**Issue by siltastic** [ga-dc/pbj#146]
Comfort Level: 5/5
Completeness: 5/5

All the reference links were helpful and informative. I found these various git commands that will be useful to me in my work environment.

* git branch -m <branch>: Rename the current branch to <branch>.
* git revert HEAD^: Undo the previous commit.
* git branch -r: List all local and remote branches.
* git blame <filename>: Show what revision and author last modified each line. Hilarious command name.

Also, if the master has not diverged from an isolated branch (a linear path), git will use a fast forward merge. It will combine both the branch and master's histories.

**Comment by jshawl** [comment]
:+1:
