### ISSUE TITLE
Git HW

### ISSUE THREAD

**Issue by pdoulatshahi** [ga-dc/pbj#147]
The most interesting thing I learned about from the Git links is rebasing vs. merging.

While merging makes the commit you are merging exist in both the branch you merge from and the branch you merge to, rebasing takes the entire branch history of the rebased branch and puts it at the end of the branch to which you are rebasing, rewriting those commits on the end of the new branch. 

I'd be interested to hear about rebasing vs. merging from instructors who've used both.

**Comment by jshawl** [comment]
:+1:

**Comment by jshawl** [comment]
I used to rebase a lot, but now I hate it. I don't like the idea of rewriting history. Yes, it makes the story shorter and easier to comprehend - but it's a lie. Here's a blog post I wrote about rebasing https://jesse.sh/interactive-rebasing-considered-harmful/
