### ISSUE TITLE
Learning Git Homework

### ISSUE THREAD

**Issue by andersenek** [ga-dc/pbj#149]
What I felt was made more clear in: https://www.atlassian.com/git/tutorials/using-branches/git-checkout was that when you check out a commit, Git switches into a “detached HEAD” state. What I now understand is that if you make changes/develop anything in a detached HEAD state and want to check out another branch to merge your work in, there is actually no way to reference the work you had done. Luckily a warning should prompt before ending up in this state but it's good to look out for so that you don't accidentally end up with a detached HEAD.

**Comment by jshawl** [comment]
:+1:
