### ISSUE TITLE
Cameron's Git AhHa Moment

### ISSUE THREAD

**Issue by cameronfry11** [ga-dc/pbj#150]
completeness: 5/5
comfort: 3.75/5 

I actually didn't know how to checkout old commits before looking through this manual. I know that I can log out previous commits, access any commit I want with the ID using the checkout command, then edit that commit, then checkout the master branch, and then to remove those changes just hit git revert or git reset. Nice!

Also, merging with conflicts. Post merge, just hit git add <file> after the fix and the files are merged.

I should really understand better than I do. I still feel like I'm going to make some boneheaded moves in git in the following weeks. . .

**Comment by jshawl** [comment]
:+1:
