### ISSUE TITLE
Learning git is like learning guitar / teaching format comparison

### ISSUE THREAD

**Issue by tomBeach** [ga-dc/pbj#153]
Learning git is like learning guitar -- you have to practice the moves from command to command, like practicing chord changes measure to measure in a song.  I'd be curious to know how people compared the three git homework links: "clean and minimalist" Atlassian vs "detailed and procedural" Git tutorial vs interactive pcottle.  Personally I liked clean and minimalist for this topic -- it gets right into the content and allows for easy extraction of command sequences.  (Per Jesse's suggestion I'm working on a command sequence cheatsheet for all basic git workflows, and this site is a goldmine for that.)  I am particularly interested in interactive training techniques (one of my job goals involves developing educational simulations) but I found the pcottle site to be a bit annoying -- too dense and time-consuming.  (Maybe I was just tired.)  I've set a "practice repo" to work with on github -- like doing scales up and down the fretboard...

**Comment by jshawl** [comment]
:+1: ah would love to hear more about your interactive education plans!!
