### ISSUE TITLE
Git Branching

### ISSUE THREAD

**Issue by jshawl** [ga-dc/pbj#155]
https://trello.com/c/jhwxZyUA/16-git-branching

**Comment by jshawl** [comment]
https://github.com/ga-dc/pbj/blob/ad168d88257bc0040c86f0770c463fec48da5e98/02-intermediate-front-end/git_branching/readme.md

**Comment by adambray** [comment]
+: Exercises overall went well. Lesson is short-ish (2 hrs)

delta: Find a way to start exercises sooner, hard to balance theory (diagrams) needed to understand what's going on, with practice (showing them, having them do it).
