### ISSUE TITLE
jquery 2

### ISSUE THREAD

**Issue by jshawl** [ga-dc/pbj#186]
https://trello.com/c/A0V4lrqm/17-jquery-part-2

**Comment by jshawl** [comment]
https://github.com/ga-dc/pbj/blob/3f3836e189cfc33fc90dd80c61ec5043b6a7e11e/02-intermediate-front-end/jquery/jquery-two.md

**Comment by andrewsunglaekim** [comment]
∆ - I think i should cut the parts that review what adrian covered to provide time for an actual in class exercise. Or just pepper more inclass ex throughout lesson. I think i did too much i do and not enough we do/you do

+ I think overall the lesson went well though despite no practical application. Definitely glad I went over the I do code a couple times on my own before instruction
