### ISSUE TITLE
git branch learning

### ISSUE THREAD

**Issue by msteffan** [ga-dc/pbj#188]
Definitely a basic thing, but we didn't cover this in class:
You can move work directly from a branch onto a master, using "rebase." By using rebase, you can move projects built in parallel in line with one another, so it looks like they were developed sequentially. I love a good organization structure, so the idea of trees and branches really doesn't do it for me. But if everything is in one sequential structure, that's much cleaner.

I've also been wondering how to revert back to previous commits in git, so it was great to learn about git reverse and git reset. The difference between reset and reverse is that one "rewrites history" while the other simply "moves back in time" to a previous commit; I can definitely see git reverse being more useful than git reset, as I often want to see previous versions but not lose my current work.

**Comment by jshawl** [comment]
:+1:
