### ISSUE TITLE
What I learned about git

### ISSUE THREAD

**Issue by puzzleboks** [ga-dc/pbj#201]
Detached HEAD: The HEAD in git is the commit that you are currently working on, a way of referring to the current snapshot. The HEAD usually points to a branch name but can be "detached" (by attaching it to a commit, instead of a branch.) Using the tilde symbol, for example, one could use 'git checkout HEAD~4' to move four levels up the commit tree, thus detaching the HEAD from the branch. Once done git provides a warning that everything done from that point on is "detached" from the rest of the development. Therefore, development should always take place on a branch, not a detached head.

**Comment by jshawl** [comment]
:+1:
