### ISSUE TITLE
CSS 2

### ISSUE THREAD

**Issue by jshawl** [ga-dc/pbj#208]
https://trello.com/c/fYK81Bn6/18-css-part-2

**Comment by jshawl** [comment]
https://github.com/ga-dc/pbj/blob/0bee928767dc3b126e227dfda0c852c72715adb2/02-intermediate-front-end/css2/readme.md

**Comment by mattscilipoti** [comment]
∆ - Tool long.  Recommend converting to Flipped Classroom style (using LearnLayout.com).
∆ - CFU for 3rd Party Fonts, 

plus - LearnLayout.com is excellent reference.
