### ISSUE TITLE
ERD

### ISSUE THREAD

**Issue by jshawl** [ga-dc/pbj#214]

**Comment by mattscilipoti** [comment]
Trello: 
Snapshot: https://github.com/ga-dc/pbj/tree/955a0c643676191f9d4fcea964540c4a0ed15c70/04-ruby-mvc-sinatra/domain_modeling

**Comment by mattscilipoti** [comment]
∆ - Needs more exercises
∆ - Conclusion is week

plus - Orchard domain model image is good example
