### ISSUE TITLE
Databases

### ISSUE THREAD

**Issue by jshawl** [ga-dc/pbj#215]
https://github.com/ga-dc/pbj/tree/master/04-ruby-mvc-sinatra/databases

**Comment by mattscilipoti** [comment]
∆ - Better dataset for JOIN examples.  The current data does not visualize the join clearly and isn't a normal use case for a join.  Suggest: using Company/Orchard form ERD lesson.
∆ - Simpler schema for table (too many required fields).
  First INSERT example (# This won't work!) issue is too subtle (missing tick in the middle somewhere).  Suggest: forgetting a required field.
+ - Nice scaffolding.  Builds upon earlier information well.
