### ISSUE TITLE
suggestion for improving homework.md

### ISSUE THREAD

**Issue by msteffan** [ga-dc/pbj#216]
Could we add a column to the table so that we know not only when something was assigned but also when it is due?

**Comment by jshawl** [comment]
@msteffan due dates can be added in the notes column. Otherwise they are due the morning after they are assigned. See https://github.com/ga-dc/pbj/blob/master/02-intermediate-front-end/homework.md#peanut-butter for an example.

Let me know if you have other ideas Thanks!
