### ISSUE TITLE
Sinatra Rest

### ISSUE THREAD

**Issue by jshawl** [ga-dc/pbj#219]

**Comment by mattscilipoti** [comment]
Delta: Layout portion requires teaching concept of view, layout, reuse AND mechanics of ERB & yield.  All at once.  Can we ease in?

**Comment by mattscilipoti** [comment]
Delta: For "post" portion: if you use "/instructors" route (vs "/"), it is more RESTful (CRUD for the instructor resource) and leads them towards choosing an appropriate route later.  It eliminates the question of which route should I use - you use the routes for the instructor resource.

**Comment by mattscilipoti** [comment]
Delta: Use "get" to illustrate params hash before going to "post".  We could do this first by typing query params in the browser and having an endpoint that just displays `params`.

**Comment by jshawl** [comment]
:+1: Awesome suggestions Matt!!! Definitely will implement and reference in the next iteration. Closing for now but further comments are welcome!

∆: Everything in this lesson is built from scratch. Focus on one thing at a time. Give a starter application and give steps to implement. 

∆: Today was the last time I'll teach w/ Sinatra and the Internal server error bug:

![](https://dl.dropboxusercontent.com/s/nongdp2n7nhdiju/Screenshot%202015-07-22%2018.56.49.png?dl=0) Fix this asap.

∆: There is a lot of assumed material in this lesson:

- The stucture of url (query string, protocol, path)
- The request/response model of HTTP

Suggest a reading or basic exercise about HTTP or TCP/IP possibly w/ `TCPServer.new`
