### ISSUE TITLE
Unit testing w/ Rspec

### ISSUE THREAD

**Issue by jshawl** [ga-dc/pbj#225]
https://trello.com/c/5abXpoYe/20-rspec

**Comment by mattscilipoti** [comment]
- Delta: clean instructions for managing rspec < 3 for test first.org.
- Delta: Need some discussion of side-effects.
- Plus: Teaching rspec & testing, rather than TDD/BDD, seemed clearer for students.  Question responses showed some understanding, rather than regurgitation.

**Comment by mattscilipoti** [comment]
Updated test first.org instructions: 83f5adce02312d4d3baaa1e725e4f5c54254091e

**Comment by mattscilipoti** [comment]
Added "Specify Side-effects" https://github.com/ga-dc/pbj/commit/25cf4ae997eade3974a238f8993cac2a543a89f3

**Comment by mattscilipoti** [comment]
Add timings https://github.com/ga-dc/pbj/commit/186543523d66f293beb967e064e2f79f7da74650
