### ISSUE TITLE
Rails Helpers

### ISSUE THREAD

**Issue by mattscilipoti** [ga-dc/pbj#229]
- https://github.com/ga-dc/pbj/tree/fa0ef306bf8e94408ae0e8447924e8514f3a75cf/05-mvc-with-rails/rails-helpers
- https://trello.com/c/GhGg89nE

**Comment by mattscilipoti** [comment]
- plus: excellent framing.  Pointing to code they are familiar with, while describing common problems.
- plus: good scaffolding of small steps.
- plus: good use of simple diagrams to answer questions.  see: https://generalassembly.slack.com/archives/dc-wdi6-instructors/p1438181210000025
- delta: We should use *_url for redirects.  http://viget.com/extend/rails-named-routes-path-vs-url

**Comment by adambray** [comment]
delta: find more ways to check for understanding. exercises were helpful, as were fist to five, but more variety would be nice.

**Comment by adambray** [comment]
delta: remove CSRF, it should be covered in V&C lesson.
