### ISSUE TITLE
Rails Sessions and Auth

### ISSUE THREAD

**Issue by mattscilipoti** [ga-dc/pbj#231]
- https://github.com/ga-dc/pbj/tree/fa0ef306bf8e94408ae0e8447924e8514f3a75cf/05-mvc-with-rails/rails-sessions-and-auth
- https://trello.com/c/OlCpCr9Q

**Comment by mattscilipoti** [comment]
- plus: Good framing.  "I have heard many of you discussing adding Users to your applications.  Today is that day."

I enjoyed this lesson and feel that it shared this information well.  There are quite a few suggestions below, but this does not reflect on the quality of the lesson.
- delta: use validations on User for required username & password.
- delta: use underscores (sign_up, sign_in)
- delta: clarifying comment (in code) about the conjoined sign_up/sign_in process.
- delta: discussion of `Rails.logger.info`, instead of `puts`?
- delta: scaffold, less code at once: i.e. handle sign_up (only sign_up code), verify, then add sign_in code and verify.
- delta: formal discussion of layouts in rails.  Should this be a delta/plus issue on Rails Views?
- delta: use standard keys for flash message (:notice, :alert), see: http://guides.rubyonrails.org/action_controller_overview.html#the-flash.  This simplifies css too.
- delta: share the decoding process earlier (on board?) - so they can understand how hashing, hash+salt will be used.
- delta: extract methods to highlight changes. Contents of `verify_password` method change, instead of "some lines" within this long controller method.
- delta: many questions about security. http vs https.  Should we include more in the lesson?  I like having students ask, but would prefer to have answers prepared for common questions.  When calling an audible, we usually miss important steps, examples, and or CFUs.

**Comment by RobertAKARobin** [comment]
I think the big takeaway is security and auth should probably be a full day.

**Comment by mattscilipoti** [comment]
Agreed.  This lesson is really compressed.

**Comment by jshawl** [comment]
∆: Provide starter code that students can git pull or curl instead of copy paste. Every error I helped fix today involved typos and/or misspellings.

+: I love how little magic there is in this lesson. You really build up authentication from the ground up. nice job!

**Comment by adambray** [comment]
@RobertAKARobin 

+: love how much this is from scratch

∆: instead of storing instances of "user" in the session, store just the user id. (storing complex objects in the session is considered an anti-pattern, as the session will fill up very quickly, and also, students don't know what serialization is yet)

∆: write a `current_user` method that loads the user from the session[:user_id], and mimics functionality from devise or best practices in hand-rolled

**Comment by adambray** [comment]
∆: put sign_up / sign_in code in a dedicated controller (e.g. SessionsController to follow SRP)

**Comment by adambray** [comment]
∆: use restful routes for user signup (following REST, it should use a `form_for` rather than `form_tag`, and route to `users#create`.

**Comment by mattscilipoti** [comment]
∆: Review cleanup as we add has_secure_password, then move to devise.  These can conflict with each other.
