### ISSUE TITLE
APIs

### ISSUE THREAD

**Issue by jshawl** [ga-dc/pbj#240]
https://trello.com/c/YpR0i2Sy/32-apis

https://github.com/ga-dc/pbj/blob/708cbfe924b36d9799c41e1415a388b4b17b7708/07-uxdi-collaboration/apis/readme.md

**Comment by jshawl** [comment]
∆: Use a tool like localtunnel.me to let students connect to development server

**Comment by mattscilipoti** [comment]
delta: Use song related 3rd party api
delta: add bonus/extra exercises

**Comment by mattscilipoti** [comment]
delta: advice from Adam.  Get into exercises sooner. Go fast earlier, slow down later.  Helpful in general, more so with this lesson.
