### ISSUE TITLE
Responsive Web Design

### ISSUE THREAD

**Issue by mattscilipoti** [ga-dc/pbj#242]
- LessonPlan: https://github.com/ga-dc/pbj/tree/df6cced109c006dfb1901af100c758b0d0111062/07-uxdi-collaboration/responsive-web-design

**Comment by mattscilipoti** [comment]
- Plus: Good framing.  Really got students involved; thinking and responding.  We want to hear the life/death experience from mobile/non-mobile experience!?!
- delta: we discussed downsides of "dedicated mobile", but there's nothing in lesson.
- Plus: animated gif to show result of 1st "You Do" was very helpful.
- plus: clearly articulating process for creating appropriate media queries
- delta: articulate it ^ in the lesson.

**Comment by jshawl** [comment]
∆: include data on % market share of mobile-only users
+: animated gifs for solutions are really useful
