### ISSUE TITLE
JS Testing

### ISSUE THREAD

**Issue by jshawl** [ga-dc/pbj#244]
https://trello.com/c/XyRBY2Xg/37-js-testing

**Comment by amaseda** [comment]
∆: Provide more explicit instructions for matcher portion of in-class exercise and homework.

**Comment by mattscilipoti** [comment]
∆: correction (of image): "Look at them side-by-side...", jasmine example should instantiate person outside of `beforeEach`:
```
describe( "a Person", function(){
  var person;
  
  beforeEach(function(){
    person = { name: "Matt" }; // hair: "purple" ?
  };
  ...
}
