### ISSUE TITLE
Sequelize

### ISSUE THREAD

**Issue by RobertAKARobin** [ga-dc/pbj#247]
Sorry about the !@#$% errors. Lesson plan fixed.

**Comment by mattscilipoti** [comment]
- plus: Callback hell discussion was on point.
- delta: instruct them to watch as you review tunr_sinatra, NOT follow along.
- delta: include specific instructions to "Download" tunr_node_hbs
  I would have sent a PR, but noticed this issue in the middle and missed the early commands

**Comment by RobertAKARobin** [comment]
Updated lesson plan re: point 3, I think. Point 2 noted. Thanks!
