### ISSUE TITLE
deploying to heroku hitting error on evn

### ISSUE THREAD

**Issue by christinelovett** [ga-dc/pbj#256]
We are trying to deploy to heroku but are having problems seemingly because of the user auth through twitter that is in a hidden env file, when we unrequire the file it complains of env not being defined, even after using heroku config:set for the needed keys/secret

2015-08-26T20:03:05.998059+00:00 app[web.1]: ReferenceError: env is not defined
2015-08-26T20:03:05.998028+00:00 app[web.1]: /app/index.js:25

Christines-MacBook-Air:wanderlist christinelovett$ heroku config
=== wander-list Config Vars
NODE_ENV:                   production
NODE_PATH:                  lib
env.twitter.callbackUrl:    http://wander-list.herokuapp.com/auth/twitter/callback
env.twitter.consumerKey:    V769viOuRdiSlz517RrZhZlGz
env.twitter.consumerSecret: zLCMoHS7Ue1NOxxvDwr8HYvhGPKmw0kzMbc8uwp6vwoXlR3tEs
Christines-MacBook-Air:wanderlist christinelovett$

**Comment by RobertAKARobin** [comment]
Uh oh. This issue's in the wrong place, Christine! Please submit them to https://github.com/ga-dc/pbj-project3

**Comment by christinelovett** [comment]
Haha thank you, Robin! I realized that a little too late. Fortunately Jesse
has helped us out and were all set!
