### ISSUE TITLE
Sass1: Basic Reuse

### ISSUE THREAD

**Issue by mattscilipoti** [ga-dc/pbj#258]
- lesson plan: 
- trello: https://trello.com/c/3rlTDu5z

**Comment by mattscilipoti** [comment]
Goals:
- No "I do"
  - students already familiar with basic programming concepts (variables etc.)
- minimal lecture.  Use sass docs.
  - break into pieces.  e.g. read, exercise on "variables".  Then, read, exercise on "@if". etc.
- PROBLEM!?!
- Get students to share You do, instead of me presenting my solution.

**Comment by jshawl** [comment]
∆: involve an ignorant typist and / or teach from the back of the classroom.
∆: include more checks for understanding https://github.com/ga-dc/pbj/tree/1dc46e7620fab380b37f0383dad1e12459de869a/10-back-and-front-of-front-end/sass1-basic-reuse

+: bringing up @import and rails asset pipeline.
