### ISSUE TITLE
please fix as was fixed in class.

### ISSUE THREAD

**Issue by LauraWN** [ga-dc/pbj#263]
In the code below, the second clickPopup (between the <b> tags) was changed from "popup" in class.

// Need to define the popup that will appear after a click.
var clickPopup = L.popup();

// Now define when and how `clickPopup` will appear.
map.on( "click", function( event ){
  <b>clickPopup<b>
  .setLatLng( event.latlng )
  .setContent( "Coordinates: " + event.latlng.toString() )
  .openOn( map );
})

**Comment by amaseda** [comment]
@LauraWN  Fixed. Thanks for the reminder!
