### ISSUE TITLE
Command Line

### ISSUE THREAD

**Issue by jshawl** [ga-dc/pbj#59]
https://trello.com/c/9JTQvvx8/1-command-line

**Comment by jshawl** [comment]
https://github.com/ga-dc/pbj/blob/ed03d00a9699558dc73aec3dd84bad8146e8a11f/01-front-end-fundamentals/command-line/readme.md

**Comment by mattscilipoti** [comment]
+: Students indicated that the pace was good, not too slow for review + learning.
∆: If we create our wdi working dir earlier, later exercises can take place in the sandbox.
