### ISSUE TITLE
Intro to Git

### ISSUE THREAD

**Issue by jshawl** [ga-dc/pbj#60]
https://trello.com/c/39Iw8TtB/3-intro-to-git

**Comment by jshawl** [comment]
https://github.com/ga-dc/pbj/blob/ed03d00a9699558dc73aec3dd84bad8146e8a11f/01-front-end-fundamentals/git/readme.md

**Comment by adambray** [comment]
+: The haiku exercise and "forking and cloning PBJ" exercise went really well. Giving clear directions about where to put folders really helps as well.
∆: Went down a rabbit hole on branching. Hard to avoid entirely, but should probably try to push all questions on branching until next lesson.
