### ISSUE TITLE
Portfolio

### ISSUE THREAD

**Issue by kristingreenslit** [ga-dc/pbj#89]
comfort_level: 4
completeness: 5
// I'm giving myself a 4 on this because I felt comfortable with the assignment, but couldn't get the custom domain to work properly. I purchased kristingreenslit.com from google but couldn't find how to create a custom subdomain as outlined in these instructions: https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/ . I tried forwarding my domain to github but that broke my site. I have a hard time believing that this wouldn't work with google, but their domain service is in beta - perhaps that's the issue?

personal github pages repo: https://github.com/kristingreenslit/kristingreenslit.github.io
URL to hosted page: kristingreenslit.github.io
forked pbj repo: https://github.com/kristingreenslit/pbj

**Comment by RobertAKARobin** [comment]
Unfortunately it's hard to say what the problem is without seeing how your site is administrated. Which hosting service do you use for your site? Or if you just have the domain, from which registrar did you buy it?
